# 1. Grant `cluster-monitoring-view` role to the `grafana-serviceaccount`
#  oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount
# 2. Get bearer token for `grafana-serviceaccount`. Update manifest.
#  oc serviceaccounts get-token grafana-serviceaccount -n thanos
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafana
  namespace: grafana-operator
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: prometheus
      secureJsonData:
        # Update bearer token to match your environment
        httpHeaderValue1: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Il9KSG5uZ3cwQ24zYUNKNmZfTmduRzZWT3FadkVMR0JTZkh3c1pVcS0xYkUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJncmFmYW5hLW9wZXJhdG9yIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdyYWZhbmEtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImIzN2JjZjcwLTU3YWMtNGM4MS04OTE5LTUzZjA5MjIwMmFkNyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpncmFmYW5hLW9wZXJhdG9yOmdyYWZhbmEtc2VydmljZWFjY291bnQifQ.A86R5NDIT2N6wrWFYuSopvRxnhCmpjbSlHdlglooQMu79hHZQHa5eKsxP2YPguL5gKAJpQGAkRiRs0EzkumSO0gL4RuW7Xe_VZGQSaCX4nw4CrcI4bcZCLGytiewNVa81-Nqjh_hQllzV-G7aHPy04xki85UEQubknt7aldh3-URVpowQUmA_l1WF9SeH4i1hRY5ri70X7FbVEnwKRHisd4KEBb6BkfAbIvfRXDOGx3K53kgrP1wfVQ_d3kQ1CvcM7T82oEJdKHj_EvniXv9ztClPMrxrih7w_vhN_6rs-A8TbBTuw_YY2Nw_PZykheBhm7k14wXbmG5XZrUDYjnKvMb5emL-nk7XkceJjzKVzKeb-2xIliVJrw1HP_cS3Q6CCTn1xoca5JVcYh-fQqB_W-qtlrs1ZVgOID-PGKZAb_zVlwrtAOpAGHpVjNC-HoyP4GLx1v0Tz39NBlPIQ55chLNn7vhrQ68CPwzxR1wzbgDYdwr3-HcNDrkR53-QzhlZBSjUjogUMMmQo5f61frYYBcu8SEBx3VpplX49PuIh3ABuVCf9iXPOkA9RQJLyIr_gzchyztvvSOtOtzd4yCOAn8bjHyCO5xogqfU0ydhqDLG8RX9kzDiwknL6UtGISk4ErKCRqf5TKS22ml-VuMK260epsTQdvxP26Ux9Jbrfc'
      type: prometheus
      url:  'https://thanos-querier-openshift-monitoring.apps.rosa.xuv78-3xtdb-xu7.pehe.p3.openshiftapps.com'
  name: prometheus-grafana.yaml
