apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: grafana-operator
  annotations:
    kubernetes.io/service-account.name: grafana-serviceaccount
type: kubernetes.io/service-account-token
